---
  - name: Install prerequisits for installation                                                                                                                                                             
    apt: name={{ item }} state=latest                                                                                                                                                                       
    with_items:                                                                                                                                                                                             
      - apt-transport-https                                                                                                                                                                                 
      - ca-certificates                                                                                                                                                                                     
      - software-properties-common                                                                                                                                                                          
  - name: install CA certificates
    apt: name=ca-certificates
  - name: add 3rd party apt repository keys
    apt_key: url='{{ item }}'
    with_items:
      - https://nginx.org/packages/keys/nginx_signing.key
      - https://www.postgresql.org/media/keys/ACCC4CF8.asc
      - https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
      - https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
      - https://download.docker.com/linux/debian/gpg
  - name: add 3rd party repositories
    apt_repository: repo='{{ item }}'
    with_items:
      - deb http://nginx.org/packages/debian/ stretch nginx
      - deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
      - deb http://www.rabbitmq.com/debian/ testing main
      - deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
  - name: update package list and upgrade
    apt: update_cache=yes upgrade=dist
  - name: install packages
    apt: name={{ item }} state=latest
    with_items:
      - nginx
      - sudo
      - ntp
      - ntpdate
      - python-psycopg2
      - postgresql
      - libpq-dev
      - python-virtualenv
      - python-pip
      - libffi-dev
      - supervisor
      - gcc
      - git
      - python-dev
      - rabbitmq-server
# Will probably be needed later
#      - redis-server
#      - docker-ce
  - name: create db users
    postgresql_user: name={{ item.name }} password={{ item.password }} encrypted=yes role_attr_flags=NOCREATEDB,NOCREATEROLE,NOSUPERUSER
    become: yes
    become_user: postgres
    with_items:
# NOTE: generate password when generating project (should be in sync wih settings!)
      - { name: '{{ project_name }}', password: 'Kr230c9Nsc' }
  - name: create db
    postgresql_db: name={{ project_name }} owner={{ project_name }} encoding='UTF-8'
    become: yes
    become_user: postgres
  - name: create directories
    file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
    with_items:
      - { path: '/var/www/{{ project_name }}/', owner: 'www-data', group: 'www-data', mode: '775' }
      - { path: '/var/www/{{ project_name }}/media/', owner: 'www-data', group: 'www-data', mode: '775' }
      - { path: '/var/log/{{ project_name }}/', owner: 'www-data', group: 'www-data', mode: '775' }
      - { path: '/usr/local/lib/{{ project_name }}/', owner: 'root', group: 'root', mode: '775' }
      - { path: '/var/lib/{{ project_name }}/celery', owner: 'nobody', group: 'nogroup', mode: '755' }
      - { path: '/var/run/{{ project_name }}/celery', owner: 'nobody', group: 'nogroup', mode: '755' }
  - name: upload config
    synchronize: dest={{ item.dest }} src={{ item.src }} owner=no group=no recursive=yes delete=yes
    with_items:
      - { dest: '/etc/nginx/', src: 'nginx/' }
      - { dest: '/etc/supervisor/conf.d/', src: 'supervisor/' }
    notify:
    - restart nginx
    - restart supervisor

